// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8Ig5Z44fnZ_cxxrvTXdqp6VNT4zBWu0',
    appId: '1:700157382762:web:9d094209efa9b332417a13',
    messagingSenderId: '700157382762',
    projectId: 'anchor-app-20260911',
    authDomain: 'anchor-app-20260911.firebaseapp.com',
    storageBucket: 'anchor-app-20260911.firebasestorage.app',
    measurementId: 'G-WXMQJH8FQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4pB57WGzG5InPY9iMW5A0Lm5lnwbEn0',
    appId: '1:700157382762:android:ba8a63f77e2cf185417a13',
    messagingSenderId: '700157382762',
    projectId: 'anchor-app-20260911',
    storageBucket: 'anchor-app-20260911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMDAg95k9DoyL1eRWUUyXli12fTXRXFo',
    appId: '1:700157382762:ios:4e5c66a9f6f21b0d417a13',
    messagingSenderId: '700157382762',
    projectId: 'anchor-app-20260911',
    storageBucket: 'anchor-app-20260911.firebasestorage.app',
    iosBundleId: 'com.example.anchorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbMDAg95k9DoyL1eRWUUyXli12fTXRXFo',
    appId: '1:700157382762:ios:4e5c66a9f6f21b0d417a13',
    messagingSenderId: '700157382762',
    projectId: 'anchor-app-20260911',
    storageBucket: 'anchor-app-20260911.firebasestorage.app',
    iosBundleId: 'com.example.anchorApp',
  );
}
